#!/usr/bin/env perl
use Dzpl
    name => 'Dist-Zilla-PluginBundle-ROKR',
    version => '0.0010',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        Config::Identity
        Dist::Zilla
        Dist::Zilla::PluginBundle::Basic
        Dist::Zilla::Plugin::PkgVersion
        Dist::Zilla::Plugin::PodWeaver
        File::Copy
        Moose

        [Test]
        Test::Most
    /;
;

{ plugin '@ROKR' }

run;
